server:
  port: 7050
  servlet:
    context-path: /PayrollService
cloud:
  aws:
    credentials:
      profile-name:
    region:
      auto: false
      static: ap-south-1b
    rds:
      instances:
        - db-instance-identifier:
          username:
          password:
          databaseName:
          readReplicaSupport: true


spring:
  application:
    name: PayrollService
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
  instance:
    hostname: localhost
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'