server:
   port: 9092
spring:
   application:
      name: mc-eureka-server
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9092/eureka/
         register-with-eureka: false
         eureka.client.fetch-registry: false