CREATE TABLE USER (
ID INTEGER IDENTITY PRIMARY KEY ,
username VARCHAR(255) NOT NULL,
usertype VARCHAR (255) NOT NULL,
emailid VARCHAR(255) NOT NULL,
mobileNumber VARCHAR(255) NOT NULL,
status VARCHAR(255) NOT NULL,
createdTS DATE ,
lastModifiedByTS DATE
);


