server:
   port: 7010
   servlet:
      context-path: /MasterCacheModule
spring:
   application:
      name: MasterCacheModule
   redis:
      host: localhost
      port: 6379

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9092/eureka/
service:
   masterUrl: http://localhost:7010/MasterCacheModule/getall